parameters:
  clash_games:
    - slug: 'snake'
      title: 'Holy Chase'
      description: 'Sammel das Holy um aufzusteigen. Ohne es, bist du nichts.'
      icon: 'ğŸ'
      path: '/games/snake/Snake.html'
      image: 'games/snake/snake.png'
    - slug: 'tetris'
      title: "Muttis Lieblingsspiel"
      description: 'Staple die BlÃ¶cke clever und erreiche den Highscore.'
      icon: 'ğŸ§©'
      path: '/games/tetris/Tetris.html'
      image: 'media/games/tetris.svg'
    - slug: 'flappy'
      title: 'Flappy Floxo'
      description: 'Fliege so weit wie mÃ¶glich durch die LÃ¼cken. Touch/Leertaste zum Flappen.'
      icon: 'ğŸ¦â€ğŸ”¥'
      path: '/games/flappy_square/flappy_square_2_tibbers_version.html'
      image: 'games/flappy_square/Tibbers_mit_Fluegel_oben.png'
